spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/gabandb001?autoReconnect=true&useSSL=false&serverTimezone=JST
#    url: jdbc:mysql://gabasv-02101.cki9ksfjmnba.ap-northeast-1.rds.amazonaws.com:3306/gabandb001
#    url: jdbc:mysql://104.198.126.171:3306/sample_db?autoReconnect=true&useSSL=false

    username: chat_user
    password: chat_user
    jmx-enabled: true
# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true
#server.port: 80
logging:
  level:
    root: DEBUG
    springframework.web: DEBUG
    org.hibernate: DEBUG
