spring:
  application:
    name: chat_spring_test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/sample?character_set_server=utf8
    username: sample_user
    password: fugafuga
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  messages:
    basename: ValidationMessages_ja
