spring:
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/sample_db?autoReconnect=true&useSSL=false
    url: jdbc:mysql://gabasv-02101.cki9ksfjmnba.ap-northeast-1.rds.amazonaws.com:3306/gabandb001
#    url: jdbc:mysql://104.198.126.171:3306/sample_db?autoReconnect=true&useSSL=false

#server.port: 5000
logging.level.org.springframework: WARN
